version: "3.1"

services:
  grafana:
    image: grafana/grafana:8.4.5
    ports:
      - 3000:3000
    expose:
      - 3000
  redis:
    image: influxdb
    volumes:
      - influx-data:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: influx
      DOCKER_INFLUXDB_INIT_PASSWORD: influx
      DOCKER_INFLUXDB_INIT_ORG: minecraft
      DOCKER_INFLUXDB_INIT_BUCKET: playercount
volumes:
  influx-data: { }